//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesaChallengePortal.DatabaseLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback : AccesaChallengePortal.Interfaces.IEntity
    {
        public int Id { get; set; }
        public Nullable<int> Grade { get; set; }
        public string Comment { get; set; }
        public int ResponseId { get; set; }
        public int UserId { get; set; }
    
        public virtual Respons Respons { get; set; }
        public virtual User User { get; set; }
    }
}
