//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesaChallengePortal.DatabaseLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respons : AccesaChallengePortal.Interfaces.IEntity
    {
        public Respons()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int Id { get; set; }
        public string ResponseData { get; set; }
        public string FilePath { get; set; }
        public int UserId { get; set; }
        public int QuestionId { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
