//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesaChallengePortal.DatabaseLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class User : AccesaChallengePortal.Interfaces.IEntity
    {
        public User()
        {
            this.Responses = new HashSet<Respons>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual ICollection<Respons> Responses { get; set; }
    }
}
